# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# SQLite (development and test)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Test environment (remains unchanged)
test:
  <<: *default
  database: db/test.sqlite3

# PostgreSQL for Production
production:
  <<: *default
  adapter: postgresql
  database: travel_journal_production  # Replace with your actual app name
  username: travel_journal
  password: <%= ENV["TRAVEL_JOURNAL_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_URL"] %>
